export {
  TemplateTypeSchema,
  type TemplateType,
  TemplateMetadataSchema,
  type TemplateMetadata,
  TemplateSchema,
  type Template,
  TemplateSummarySchema,
  type TemplateSummary,
  CreateTemplateRequestSchema,
  type CreateTemplateRequest,
  UpdateTemplateMetadataRequestSchema,
  type UpdateTemplateMetadataRequest,
  GlobalWishesTemplateMetadataSchema,
  type GlobalWishesTemplateMetadata,
  GlobalWishesTemplateContentSchema,
  type GlobalWishesTemplateContent,
} from '@/src/entities/models/template.model';
