'use client';

import React, {useState} from 'react';
import {
    AlertDialog,
    AlertDialogAction,
    AlertDialogCancel,
    AlertDialogContent,
    AlertDialogDescription,
    AlertDialogFooter,
    AlertDialogHeader,
    AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Label} from '@/components/ui/label';
import {Loader2} from 'lucide-react';

interface ImportMultipleSolutionsDialogProps {
    open: boolean;
    onOpenChange: (open: boolean) => void;
    caseId: number;
    start: string;
    end: string;
    solutionCount: number;
    feasibleSolutions?: number[]; // Indices of feasible solutions (e.g., [0, 1, 2] or [0, 2] if w1 failed)
    onImport: (params: {
        caseId: number;
        start: string;
        end: string;
        solutionType: string;
    }) => Promise<void>;
    isImporting: boolean;
}

/**
 * Dialog that allows importing multiple solutions generated by solve-multiple.
 */
export function ImportMultipleSolutionsDialog({
                                                  open,
                                                  onOpenChange,
                                                  caseId,
                                                  start,
                                                  end,
                                                  solutionCount,
                                                  feasibleSolutions,
                                                  onImport,
                                                  isImporting,
                                              }: ImportMultipleSolutionsDialogProps) {
    // Use feasibleSolutions if provided, otherwise default to all solutions (backward compatibility)
    const availableSolutions = feasibleSolutions || Array.from({length: solutionCount}, (_, i) => i);

    const [selectedSolutions, setSelectedSolutions] = useState<Set<number>>(
        new Set(availableSolutions)
    );
    const [error, setError] = useState<string | null>(null);
    const [importProgress, setImportProgress] = useState<{
        current: number;
        total: number;
    } | null>(null);

    // Reset state when dialog is closed or when feasible solutions change
    React.useEffect(() => {
        if (!open) {
            setError(null);
            setImportProgress(null);
            setSelectedSolutions(new Set(availableSolutions));
        }
    }, [open, availableSolutions]);

    const handleToggle = (index: number) => {
        const newSelected = new Set(selectedSolutions);
        if (newSelected.has(index)) {
            newSelected.delete(index);
        } else {
            newSelected.add(index);
        }
        setSelectedSolutions(newSelected);
    };

    const handleSelectAll = () => {
        setSelectedSolutions(new Set(availableSolutions));
    };

    const handleSelectNone = () => {
        setSelectedSolutions(new Set());
    };

    const handleImport = async () => {
        if (selectedSolutions.size === 0) {
            setError('Bitte wählen Sie mindestens eine Lösung aus');
            return;
        }

        setError(null);
        setImportProgress({current: 0, total: selectedSolutions.size});

        try {
            let current = 0;
            for (const index of Array.from(selectedSolutions).sort()) {
                current++;
                setImportProgress({current, total: selectedSolutions.size});

                const solutionType = `w${index}`;
                await onImport({caseId, start, end, solutionType});
            }

            setImportProgress(null);
            onOpenChange(false);
        } catch (err) {
            setError(err instanceof Error ? err.message : 'Fehler beim Importieren');
            setImportProgress(null);
        }
    };

    const handleCancel = () => {
        setError(null);
        setImportProgress(null);
        onOpenChange(false);
    };

    const formatDate = (dateStr: string) => {
        const date = new Date(dateStr);
        return date.toLocaleDateString('de-DE', {
            year: 'numeric',
            month: '2-digit',
            day: '2-digit',
        });
    };

    const getSolutionLabel = (index: number): string => {
        const labels = ['Standard-Gewichte', 'Wochenend-Fokus', 'Nachtschicht-Optimierung'];
        return labels[index] || `Lösung ${index + 1}`;
    };

    return (
        <AlertDialog open={open} onOpenChange={onOpenChange}>
            <AlertDialogContent className="max-w-2xl">
                <AlertDialogHeader>
                    <AlertDialogTitle>Lösungen importieren</AlertDialogTitle>
                    <AlertDialogDescription>
                        {availableSolutions.length === 3
                            ? 'Der Solver hat 3 Lösungen erfolgreich erstellt. Wählen Sie aus, welche Sie importieren möchten.'
                            : `Der Solver konnte nur ${availableSolutions.length} von 3 Lösungen erfolgreich erstellen. Wählen Sie aus, welche Sie importieren möchten.`
                        }
                    </AlertDialogDescription>
                </AlertDialogHeader>
                <div className="space-y-4">
                    <div className="rounded-md bg-muted p-3 text-sm">
                        <div className="space-y-1 text-muted-foreground">
                            <div>Fall: {caseId}</div>
                            <div>Zeitraum: {formatDate(start)} - {formatDate(end)}</div>
                        </div>
                    </div>

                    {availableSolutions.length < 3 && (
                        <div className="rounded-md bg-yellow-500/10 border border-yellow-500/20 p-3 text-sm">
                            <div className="font-medium text-yellow-600 dark:text-yellow-500 mb-1">⚠️ Nicht alle
                                Lösungen erfolgreich
                            </div>
                            <div className="text-yellow-700 dark:text-yellow-400 text-xs">
                                {3 - availableSolutions.length} von 3 Lösungen konnten nicht generiert werden (kein
                                FEASIBLE Status).
                                {availableSolutions.length > 0
                                    ? ' Die verfügbaren Lösungen können trotzdem importiert werden.'
                                    : ' Es können keine Lösungen importiert werden.'
                                }
                            </div>
                        </div>
                    )}

                    <div className="space-y-3">
                        <div className="flex justify-between items-center">
                            <Label className="text-sm font-medium">Lösungen auswählen:</Label>
                            <div className="flex gap-2 text-xs">
                                <button
                                    type="button"
                                    onClick={handleSelectAll}
                                    className="text-primary hover:underline"
                                    disabled={isImporting}
                                >
                                    Alle
                                </button>
                                <span className="text-muted-foreground">|</span>
                                <button
                                    type="button"
                                    onClick={handleSelectNone}
                                    className="text-primary hover:underline"
                                    disabled={isImporting}
                                >
                                    Keine
                                </button>
                            </div>
                        </div>

                        <div className="space-y-2">
                            {availableSolutions.map((i) => (
                                <div
                                    key={i}
                                    className="flex items-center space-x-3 rounded-md border p-3 hover:bg-muted/50"
                                >
                                    <Checkbox
                                        id={`solution-${i}`}
                                        checked={selectedSolutions.has(i)}
                                        onCheckedChange={() => handleToggle(i)}
                                        disabled={isImporting}
                                    />
                                    <Label
                                        htmlFor={`solution-${i}`}
                                        className="flex-1 cursor-pointer text-sm font-normal"
                                    >
                                        <span className="font-medium">w{i}</span> - {getSolutionLabel(i)}
                                    </Label>
                                </div>
                            ))}
                        </div>
                    </div>

                    {importProgress && (
                        <div className="rounded-md bg-primary/10 p-3 text-sm">
                            <div className="flex items-center gap-2">
                                <Loader2 className="h-4 w-4 animate-spin"/>
                                <span>
                  Importiere Lösung {importProgress.current} von {importProgress.total}...
                </span>
                            </div>
                        </div>
                    )}

                    {error && (
                        <div className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">
                            {error}
                        </div>
                    )}
                </div>
                <AlertDialogFooter>
                    <AlertDialogCancel onClick={handleCancel} disabled={isImporting}>
                        Abbrechen
                    </AlertDialogCancel>
                    <AlertDialogAction onClick={handleImport} disabled={isImporting || selectedSolutions.size === 0}>
                        {isImporting ? (
                            <>
                                <Loader2 className="mr-2 h-4 w-4 animate-spin"/>
                                Importiere...
                            </>
                        ) : (
                            `${selectedSolutions.size} ${selectedSolutions.size === 1 ? 'Lösung' : 'Lösungen'} importieren`
                        )}
                    </AlertDialogAction>
                </AlertDialogFooter>
            </AlertDialogContent>
        </AlertDialog>
    );
}
