import { NextResponse } from 'next/server';
import { listCases, createCase } from '@/lib/data/case/db-case';
import { createApiLogger } from '@/lib/logging/logger';

const apiLogger = createApiLogger('/api/cases');

/**
 * GET /api/cases
 * Retrieves a list of all available case IDs.
 * 
 * Cases are scanned from the file system (cases/ directory).
 * Each case has its own directory containing its data files.
 * 
 * @returns JSON object with an array of case IDs
 * @returns 500 error if the operation fails
 */
export async function GET() {
  const method = 'GET';
  try {
    apiLogger.info('Listing cases', { method });
    const cases = await listCases();
    apiLogger.info('Listed cases', { method, count: cases.length });
    return NextResponse.json({ cases });
  } catch (error) {
    apiLogger.error('Failed to list cases', { method, error });
    return NextResponse.json({ error: 'Failed to list cases' }, { status: 500 });
  }
}

/**
 * POST /api/cases
 * Creates a new case with a unique ID.
 * 
 * The new case ID is automatically generated by incrementing the highest existing ID.
 * A new directory and case_information.json file are created for the case.
 * 
 * @returns JSON object with the newly created case ID
 * @returns 500 error if the operation fails
 */
export async function POST() {
  const method = 'POST';
  try {
    apiLogger.info('Creating case', { method });
    const newCaseId = await createCase();
    apiLogger.info('Created case', { method, caseId: newCaseId });
    return NextResponse.json({ caseId: newCaseId });
  } catch (error) {
    apiLogger.error('Failed to create case', { method, error });
    return NextResponse.json({ error: 'Failed to create case' }, { status: 500 });
  }
}
